config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'likes/index'

  get 'incoming/create'

  resources :topics do
    resources :bookmarks, except: :index
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:index, :create, :destroy]
  end

  root 'welcome#index'

  get 'welcome/about'

  get 'welcome/after_sign_up'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]

  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  default_scope { order('created_at DESC')}
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks

  default_scope { order('title ASC')}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    if bookmark
      likes.where(bookmark_id: bookmark.id).first
    end
  end

  def liked_bookmarks
    likes.includes( bookmark: :topic ).map(&:bookmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.create(bookmark_params)
    @bookmark.user = current_user

    if @bookmark.save
      flash[:notice] = "Bookmark was saved."
      redirect_to @bookmark.topic
    else
      flash.now[:alert] = "There was an error saving the bookmark. Please try again."
      redirect_to @bookmark.topic
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was updated."
      redirect_to topic_path(@topic)
    else
      flash.now[:alert] = "There was an error updating the bookmark. Please try again."
      redirect_to topic_path(@topic)
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted."
      if @topic.bookmarks.count == 0
        @topic.destroy
      end
      redirect_to topics_path
    else
      flash.now[:alert] = "There was an error deleting the bookmark. Please try again."
      redirect_to topic_path(@topic)
    end


  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!

  def create
    @user = User.find_by_email(params[:sender])
    @topic = Topic.find_or_create_by(title: params[:subject])
    @bookmark = @topic.bookmarks.find_or_create_by(url: params["body-plain"])

    if @user.nil?
      @user = User.create!(email: params[:sender], password: "helloworld", password_confirmation: "helloworld")
    end

    @bookmark.save
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    if like.save
      flash[:notice] = "Bookmark was liked."
    else
      flash.now[:alert] = "There was an error liking that bookmark. Please try again."
    end
    redirect_to @bookmark.topic
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    if like.destroy
      flash[:notice] = "Bookmark was unliked."
    else
      flash.now[:alert] = "There was an error un-liking that bookmark. Please try again."
    end
    redirect_to @bookmark.topic
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    welcome_after_sign_up_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      flash[:notice] = "Topic was created."
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error creating the topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error updating the topic. Please try again."
      render :edit
    end
  end

  def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy && (@topic.bookmarks.count == 0)
       flash[:notice] = "Topic was deleted."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic. Please try again."
       render :show
     end
   end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def after_sign_up
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'embedly'
  require 'json'

  def display(url)
    embedly_api = Embedly::API.new(key: ENV['EMBEDLY_API_KEY'])

    obj = embedly_api.extract :url => url
    obj.first.favicon_url
  end

  def describe(url)
    embedly_api = Embedly::API.new(key: ENV['EMBEDLY_API_KEY'])

    obj = embedly_api.oembed :url => url
    obj.first.description
  end

  def title(url)
    embedly_api = Embedly::API.new(key: ENV['EMBEDLY_API_KEY'])

    obj = embedly_api.extract :url => url
    obj.first.provider_name
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Edit Blocmark</h1>

<div class="row">
  <div class="col-md-4">
    <h2>Guidelines for bookmarks:</h2>
    <ul>
      <li>No inappropriate content allowed.</li>
      <li>Have fun!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@bookmark.topic, @bookmark] do |f| %>
    <div class="form-group">
      <%= f.label :Url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter the URL" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Back", topic_path(@bookmark.topic), class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>

app/views/bookmarks/new.html.erb
<h1>New Blocmark</h1>

<div class="row">
  <div class="col-md-4">
    <h2>Guidelines for bookmarks:</h2>
    <ul>
      <li>No inappropriate content allowed.</li>
      <li>Have fun!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @bookmark] do |f| %>
    <div class="form-group">
      <%= f.label :Url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter the URL" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Back", topic_path(@topic), class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>

app/views/bookmarks/show.html.erb
<div class="jumbotron">
  <%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>
</br>
  <div>
    <h2>
      <%= link_to @bookmark.url, "http://#{@bookmark.url}" %>
    </h2>
    <div>
      <h3><%= describe("http://#{@bookmark.url}") %></h3>
    </div>
    <% if policy(@bookmark).edit? %>
      <%= link_to "Edit Bookmark", edit_topic_bookmark_path(@bookmark.topic, @bookmark), class: "btn btn-warning" %>
    <% end %>
    <% if policy(@bookmark).destroy? %>
      <%= link_to "Delete Bookmark", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this bookmark?'} %>
    <% end %><br>
    <%= link_to "Return to All", topics_path, class: 'btn btn-primary' %>
    <%= link_to "Return to Topic", topic_path(@bookmark.topic), class: 'btn btn-primary' %>
  </div>
</div>

app/views/incoming/create.html.erb
<h1>Incoming#create</h1>
<p>Find me in app/views/incoming/create.html.erb</p>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
   <div>
     <% if like = current_user.liked(bookmark) %>
       <%= link_to [bookmark, like], class: 'btn btn-danger pull-right', method: :delete do %>
         <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
       <% end %>
     <% else %>
       <%= link_to [bookmark, Like.new], class: 'btn btn-info pull-right', method: :post do %>
         <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
       <% end %>
     <% end %>
   </div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <h2>Guidelines for topics:</h2>
    <ul>
      <li>No inappropriate content allowed.</li>
      <li>Don't use all CAPS.</li>
      <li>Have fun!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Back", topics_path, class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
<h1>All Blocmarks</h1>
<div>
  <%= link_to "New Topic", new_topic_path, class: "btn btn-success" %>
</div>
<div class="row">
  <div class="col-md-12">
    <% @topics.each do |topic| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to topic.title, topic %>
        </h4>
          <% topic.bookmarks.each do |link| %>
          <ul>
            <li class="well">
              <div>
                <%= render partial: 'likes/like', locals: { bookmark: link } %>
                <%= link_to image_tag(display("http://#{link.url}"), class: "favicon"), topic_bookmark_path(link.topic, link) %>
                <%= link_to title("#{link.url}"), topic_bookmark_path(link.topic, link) %>
              </div>
            </li>
          </ul>
            <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <h2>Guidelines for topics:</h2>
    <ul>
      <li>No inappropriate content allowed.</li>
      <li>Don't use all CAPS.</li>
      <li>Have fun!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Back", topics_path, class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
<h1><%= (@topic.title) %>
  <small>
     <%= link_to "Edit", edit_topic_path, class: "btn btn-warning btn-sm" %>
     <%= link_to "Back", topics_path, class: "btn btn-primary btn-sm" %>
     <%= link_to "New Blocmark", new_topic_bookmark_path(@topic), class: "btn btn-success pull-right" %>
   </small>
</h1>
<div class="row">
  <div class="col-md-12">
    <div class="media">
      <div class="media-body">
        <% @topic.bookmarks.each do |link| %>
        <ul>
          <li class="well">
            <%= render partial: 'likes/like', locals: { bookmark: link } %>
            <%= link_to image_tag(display("http://#{link.url}"), class: "favicon"), topic_bookmark_path(link.topic, link)  %>
            <%= link_to title("#{link.url}"), topic_bookmark_path(link.topic, link) %>
          </li>
          </ul>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="media">
      <h2>My Blocmarks</h2>

      <div class="media-body">
        <% @user_bookmarks.each do |bookmark| %>
          <ul>
            <li class="well">

              <%= link_to image_tag(display("http://#{bookmark.url}"), class: "favicon"), topic_bookmark_path(bookmark.topic, bookmark) %>
              <%= link_to title("#{bookmark.url}"), topic_bookmark_path(bookmark.topic, bookmark) %>
              <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
              <div>
                  <% if policy(bookmark).edit? %>
                  <%= link_to "Edit Bookmark", edit_topic_bookmark_path(bookmark.topic, bookmark), class: "btn btn-warning btn-xs" %>
                <% end %>
                  <% if policy(bookmark).destroy? %>
                  <%= link_to "Delete Bookmark", [bookmark.topic, bookmark], method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: 'Are you sure you want to delete this bookmark?'} %>
                <% end %>
              </div>
            </li>
          </ul>
          <% end %>
      </div>
      <h2>My Likes</h2>

      <div class="media-body">
        <% @liked_bookmarks.each do |bookmark| %>
          <ul>
            <li class="well">
              <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
              <%= link_to image_tag(display("http://#{bookmark.url}"), class: "favicon"), topic_bookmark_path(bookmark.topic, bookmark) %>
              <%= link_to title("#{bookmark.url}"), topic_bookmark_path(bookmark.topic, bookmark) %>
            </li>
          </ul>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about.html.haml
%h1 About Blocmarks
.jumbotron
  %p
    Blocmarks is an application that allows a user to bookmark URLs via email,
    peruse other user's bookmarks and maintain a personal index of categorized bookmarks.
  %small Created By: Stephen Wentling

app/views/welcome/after_sign_up.html.haml
.jumbotron
  %h1 Welcome to Blocmarks!
  %p
    Please check the e-mail which you used to sign up within the next 7 days for
    a confirmation link. Otherwise, your account may become locked. Happy bookmarking!

app/views/welcome/index.html.haml
%h1 Blocmarks: Bookmark Sharing
.jumbotron.main
  %p Feel free to create a free account and explore the world of Blocmarks.
  - if user_signed_in?
    =link_to "My Blocmarks", users_show_path, class: 'btn btn-primary btn-lg'
    =link_to "All Blocmarks", topics_path, class: 'btn btn-primary btn-lg'
  - else
    =link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-lg'
    =link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-lg'
.row
  .col-md-4.feature
    %h4 Bookmark URLs via email.
  .col-md-4.feature
    %h4 Peruse other bookmarks in the Blocmark system.
  .col-md-4.feature
    %h4 Maintain a personal index of categorized bookmarks.